HH/Controllers/ObservationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HH.DB.Models;
using HH.ViewModels;
using HH.DBQueries;
using HH.DBQueries.DTOs;



namespace HH.Controllers
{
    public class ObservationsController : Controller
    {
        private HousingHealthDB db = new HousingHealthDB();

        // GET: Observations
        public ActionResult Index()
        {
            return View(db.Observations.ToList());
        }

        // GET: Observations/Create
        public ActionResult Create()
        {
            return View();
        }
        

        // POST: Observations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Observation_Types,time_stamp,value")] Observations observations)
        {
            if (ModelState.IsValid)
            {
                db.Observations.Add(observations);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(observations);
        }


        public ActionResult ObservationResults()
        {
            return View();
           
        }


        public ActionResult ObservationSearch()
        {
            return View();
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult ObservationSearch(ObservationsViewModel vm)
        {
            var obs = db.Observations;
            QueryMethods qm = new QueryMethods();

            if (vm.Parcel != null)
            {
                List<ObservationDTO> obList = qm.ObservationSearchByParcel(vm.Parcel);

                List<ObservationsViewModel> vmList = new List<ObservationsViewModel>();

                foreach (var item in obList)
                {
                    ObservationsViewModel vmRec = new ObservationsViewModel();
                    vmRec.Number = item.Number;
                    vmRec.Street = item.Street;
                    vmRec.Parcel = item.Parcel;
                    vmRec.Observation_Types = item.Observation_Types;
                    vmRec.time_stamp = item.time_stamp;
              
                    vmList.Add(vmRec);
                }

                return View("ObservationResults", vmList);

            }
            else if (vm.Number !=null)
            {

                List<ObservationDTO> obList = qm.ObservationSearchByNumber(vm.Number);

                List<ObservationsViewModel> vmList = new List<ObservationsViewModel>();

                foreach (var item in obList)
                {
                    ObservationsViewModel vmRec = new ObservationsViewModel();
                    vmRec.Number = item.Number;
                    vmRec.Street = item.Street;
                    vmRec.Parcel = item.Parcel;
                    vmRec.Observation_Types = item.Observation_Types;
                    vmRec.time_stamp = item.time_stamp;

                    vmList.Add(vmRec);
                }

                return View("ObservationResults", vmList);
               
            }
            else
                return null;
        }
    
    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            db.Dispose();
        }
        base.Dispose(disposing);
    }
}
}

HH/Controllers/PropertiesController.cs
using HH.DB.Models;
using HH.ViewModels;
using HH.DBQueries;
using HH.DBQueries.DTOs;
using HH.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;
using HH.Business;
using System.Collections.Generic;


namespace HH.Controllers
{
    public class PropertiesController : Controller
    {
        QueryMethods qm = new QueryMethods();  

        // GET: Properties
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Search()
        {
            return View();
        }


        public ActionResult SearchByPropertyID(int PropID)
        {
            PropertiesViewModels pr = new PropertiesViewModels();

            PropertyDTO res = qm.GetPropertyInfoByID(PropID);

            pr.ID = res.ID;
            pr.Parcel = res.Parcel;
            pr.Date = res.Date;
            pr.Towner = res.Towner;
            pr.Lsaleamt = res.Lsaleamt;
            pr.Number = res.Number;
            pr.Street = res.Street;
            pr.BLOCK10 = res.BLOCK10;
            pr.BLOCKGR10 = res.BLOCKGR10;
            pr.Tract10 = res.Tract10;
            pr.Pclass = res.Pclass;
            pr.Luc = res.Luc;
            pr.Luc_descr = res.Luc_descr;
            pr.Yrbuilt = res.Yrbuilt;
            pr.MAILNAME = res.MAILNAME;
            pr.Mailname1 = res.Mailname1;
            pr.MAIL_STREET_NUMBER = res.MAIL_STREET_NUMBER;
            pr.MAIL_STREET_DIRECTION = res.MAIL_STREET_DIRECTION;
            pr.MAIL_STREET_NAME = res.MAIL_STREET_NAME;
            pr.MAIL_STREET_SUFFIX = res.MAIL_STREET_SUFFIX;
            pr.MAIL_CITY = res.MAIL_CITY;
            pr.MAIL_STATE = res.MAIL_STATE;
            pr.MAIL_ZIPCODE = res.MAIL_ZIPCODE;
            pr.TOTAL_NET_DELQ_BALANCE = Convert.ToDecimal(res.TOTAL_NET_DELQ_BALANCE);

            return View("Results", pr);
        }




        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Search([Bind(Include = "Number,Street")] PropertiesViewModels pr)
        {
            if (ModelState.IsValid)
            {
                if (pr.Number == null || pr.Street == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
            }           

            PropertyDTO res = qm.GetPropertyInfo(pr.Number, pr.Street);

            if (res == null)
            {
                ViewBag.Msg = "No Record found for this property address.  Please try again.";
                return View("Results");
            }


            qm.SaveSearchHistory(res.ID, User.Identity.GetUserId());

            pr.ID = res.ID;
            pr.Parcel = res.Parcel;
            pr.Date = res.Date;
            pr.Towner = res.Towner;
            pr.Lsaleamt = res.Lsaleamt;
            pr.Number = res.Number;
            pr.Street = res.Street;
            pr.BLOCK10 = res.BLOCK10;
            pr.BLOCKGR10 = res.BLOCKGR10;
            pr.Tract10 = res.Tract10;
            pr.Pclass = res.Pclass;
            pr.Luc = res.Luc;
            pr.Luc_descr = res.Luc_descr;
            pr.Yrbuilt = res.Yrbuilt;
            pr.MAILNAME = res.MAILNAME;
            pr.Mailname1 = res.Mailname1;
            pr.MAIL_STREET_NUMBER = res.MAIL_STREET_NUMBER;
            pr.MAIL_STREET_DIRECTION = res.MAIL_STREET_DIRECTION;
            pr.MAIL_STREET_NAME = res.MAIL_STREET_NAME;
            pr.MAIL_STREET_SUFFIX = res.MAIL_STREET_SUFFIX;
            pr.MAIL_CITY = res.MAIL_CITY;
            pr.MAIL_STATE = res.MAIL_STATE;
            pr.MAIL_ZIPCODE = res.MAIL_ZIPCODE;
            pr.TOTAL_NET_DELQ_BALANCE = Convert.ToDecimal(res.TOTAL_NET_DELQ_BALANCE);
                        
            return View("Results", pr);
        }

        public ActionResult SavedProperties()
        {
            string UserID = User.Identity.GetUserId();

            var results = qm.GetSavedProperties(UserID);
            List<SavedPropertiesVM> spList = new List<SavedPropertiesVM>();

            foreach (var item in results)
            {
                spList.Add(new SavedPropertiesVM()
                {
                    ID = item.ID,
                    IsActive = item.IsActive,
                    CreatedByDate = item.CreatedByDate,
                    PropertyAddress = item.PropertyAddress,
                    User_ID = UserID,
                    PropID = item.propertyRec.ID
                });
            }

            return View(spList);
        }

        
        public string SaveProperty(int ID)
        {
            string UserID = User.Identity.GetUserId();

            var message = qm.SaveProperty(ID, UserID);

            ViewBag.Message = message;

            return ViewBag.Message;
        }
        

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public JsonResult JsonDelete(DeleteSavedProperty model)
        {
            HousingHealthDB db = new HousingHealthDB();
            var userID = db.Users.Find(User.Identity.GetUserId()); //Paula change

            bool isDeleted = false;
            string message;

            SavedProperties sProp = db.SavedProperties.Find(model.ID);

            if (sProp == null)
            {
                message = "Failed";
                return Json(message, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var propDelete = qm.DeleteProperty(model.ID, userID.Id.ToString());
                isDeleted = true;
            }

            if (isDeleted)
                db.SaveChanges();
            message = "Saved Property Has Been Deleted";
            return Json(message, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Results()
        {
            return View();
        }
        
        public ActionResult SavePropToCompare(int? ID)
        {
            Session["ComparePropIDs"] += ID.ToString() + ",";
            return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
        }

        public ActionResult CompareProp()
        {
            //string ses = Session["ComparePropIDs"].ToString();
            //string[] arSessions = ses.Split(',');
            string[] arSessions = new string[] { "100", "202", "303", "404" };
            
            List<PropertiesViewModels> vmList = new List<PropertiesViewModels>();

            QueryMethods qm = new QueryMethods();

            foreach (var item in arSessions)
            { 
            PropertyDTO propDTO = qm.GetPropertyInfoByID(Convert.ToInt32(item));
                PropertiesViewModels propVM = new PropertiesViewModels();

                propVM.Parcel = propDTO.Parcel;
                propVM.Date = propDTO.Date;
                propVM.Towner = propDTO.Towner;
                propVM.Lsaleamt = propDTO.Lsaleamt;
                propVM.Number = propDTO.Number;
                propVM.Street = propDTO.Street;
                propVM.BLOCK10 = propDTO.BLOCK10;
                propVM.BLOCKGR10 = propDTO.BLOCKGR10;
                propVM.Tract10 = propDTO.Tract10;
                propVM.Pclass = propDTO.Pclass;
                propVM.Luc = propDTO.Luc;
                propVM.Luc_descr = propDTO.Luc_descr;
                propVM.Yrbuilt = propDTO.Yrbuilt;
                propVM.MAILNAME = propDTO.MAILNAME;
                propVM.Mailname1 = propDTO.Mailname1;
                propVM.MAIL_STREET_NUMBER = propDTO.MAIL_STREET_NUMBER;
                propVM.MAIL_STREET_DIRECTION = propDTO.MAIL_STREET_DIRECTION;
                propVM.MAIL_STREET_NAME = propDTO.MAIL_STREET_NAME;
                propVM.MAIL_STREET_SUFFIX = propDTO.MAIL_STREET_SUFFIX;
                propVM.MAIL_CITY = propDTO.MAIL_CITY;
                propVM.MAIL_STATE = propDTO.MAIL_STATE;
                propVM.MAIL_ZIPCODE = propDTO.MAIL_ZIPCODE;
                propVM.TOTAL_NET_DELQ_BALANCE = Convert.ToDecimal(propDTO.TOTAL_NET_DELQ_BALANCE);

                vmList.Add(propVM);
            }
            return View(vmList);
        }


        [HttpPost]
        public ActionResult Create([Bind(Include = "number, street")] ViewModels.PropertiesViewModels results)
        {

            if (ModelState.IsValid)
            {
                return RedirectToAction("Search");
            }
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Map()
        {
            return View();
        }

        public ActionResult SearchAddr()
        {
            return View();
        }


        [HttpPost]
        public ActionResult SearchAddr(string address)
        {
            ViewBag.Address = address;
            return View();
        }

        public ActionResult DisplayMarkers()
        {
            return View();
        }

        public ActionResult HistoryScoreResult()
        {
            
            return View();

        }


        public ActionResult HistoryScoreSearch()
        {
            return View();
        }


        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult HistoryScoreSearch(HistoryScoreViewModel vm)
        {
            QueryMethods qm = new QueryMethods();

            if (vm.Parcel != null)
            {
                List<HistoryScoreDTO> obList = qm.HistoryScoreSearchByParcel(vm.Parcel);

                List<HistoryScoreViewModel> vmList = new List<HistoryScoreViewModel>();

                foreach (var item in obList)
                {
                    HistoryScoreViewModel vmRec = new HistoryScoreViewModel();
                    vmRec.Number = item.Number;
                    vmRec.Street = item.Street;
                    vmRec.Parcel = item.Parcel;
                    vmRec.RateOfComplaints = item.RateOfComplaints;

HH/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Housing Health Application</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <!-- Latest compiled and minified CSS -->
    @*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">*@

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script type="text/javascript" src="~/Scripts/jquery-3.3.1.min.js"></script>

    <script src="~/Scripts/jquery-3.3.1.js"></script>
</head>

<body>
    
    <div class="NavLogoContain">
        <div class="hh_topnav" id="myTopnav">
            <a href="~/Home/Index" class="active">Home</a>

            <div class="hh_dropdown">
                <button class="hh_dropbtn">
                    Search Properties
                    <i class="fa fa-caret-down"></i>
                </button>
                <div class="hh_dropdown-content">
                    @Html.ActionLink("Search Property", "Search", "Properties")

                    @Html.ActionLink("Search History", "SearchHistory", "Properties")

                    @Html.ActionLink("Saved Properties", "SavedProperties", "Properties")
                </div>
            </div>
            <div class="hh_dropdown">
                <button class="hh_dropbtn">
                    Property Reports
                    <i class="fa fa-caret-down"></i>
                </button>
                <div class="hh_dropdown-content">
                    @Html.ActionLink("Property Reports", "ObservationSearch", "Observations")
                    
                    @Html.ActionLink("Lead Risks", "LeadRisks", "Properties")
                    
                    @Html.ActionLink("Other Hazards", "OtherHazards", "Properties")
                    
                    @Html.ActionLink("Other Issues", "OtherIssues", "Properties")
                    
                    @Html.ActionLink("Property Score", "PropertyScore", "Properties")
                    
                    @Html.ActionLink("History Score", "HistoryScoreSearch", "Properties")
                    
                    @Html.ActionLink("Compare Properties", "CompareProp", "Properties")
                </div>
            </div>
            @Html.ActionLink("News", "News", "Home")

            @Html.ActionLink("Contact", "Contact", "Home")

            @Html.ActionLink("About", "About", "Home")

            <a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="navigationHH()">&#9776;</a>
            @Html.Partial("_LoginPartial")
        </div>

        <div id="logo">
            <a href="~/Home/Index"><img src="~/images/CClogo.png" id="logoimg" style="height:60px !important;" /></a>   
        </div>

        <div class="container body-content">
            @RenderBody()
            <hr />

            <footer id="footer">
                <p>&copy; @DateTime.Now.Year - Housing Health </p>
            </footer>

        </div>
    </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)

        <script>
            function navigationHH() {
                var x = document.getElementById("myTopnav");
                if (x.className === "hh_topnav") {
                    x.className += " responsive";
                } else {
                    x.className = "hh_topnav";
                }
            }
        </script>
       
</body>

</html>